### ISSUE TITLE
#VS2017 file could not be found

### ISSUE THREAD

**Issue by Lynnhan95** [teodorplop/OpenGL-Water#1]
OpenGL - Shaders.vcxproj could not be found when opened in Visual Studio 2017

**Comment by Laach** [comment]
The project file is still missing, so it is still not possible to open the project in visual studio regardless of which version of visual studio is used.

**Comment by teodorplop** [comment]
Wow, sorry for that! Didn't expect people to be interested in this repository. I uploaded the project file. Hopefully it is fixed now.
