### ISSUE TITLE
Textures folder is missing?

### ISSUE THREAD

**Issue by Duplex3345678** [teodorplop/OpenGL-Water#2]
Missing the Textures folder and the png file such like heightMap.png, dudv.png, normal.png and grass.png

Do they ignore by .gitinore?

**Comment by Berzeger** [comment]
Yeah *.png is in .gitignore. Will there be an update for this?

**Comment by teodorplop** [comment]
@Duplex3345678 @Berzeger 

Oh God, I had no idea someone is actually using this, I apologize. I just added the textures now. Can you please check if your issues are fixed?

**Comment by Berzeger** [comment]
Wow, I didn't expect you to respond! :) 
Yeah, it works now, thank you very much!

> I had no idea someone is actually using this

You're the first Google result for "water renderer c++" :)

**Comment by teodorplop** [comment]
> Wow, I didn't expect you to respond! :)

Haha, yeah. I started working more on some personal projects so I'm quite active on GitHub now. 

> You're the first Google result for "water renderer c++" :)

Didn't know that, thanks for sharing. I'll work on improving what's here then.
